### ISSUE TITLE
Unable to build with ruby version 2.4.2

### ISSUE THREAD

**Issue by shadyproject** [SciRuby/rb-gsl#56]
I'm trying to build rb-gsl as part of the sciruby-full meta gem.  Currently, fails with the error 

> error.c:83:66: error: ‘rb_cFixnum’ undeclared (first use in this function)
   pgsl_error[-2] = rb_define_class_under(mgsl_error, "CONTINUE", rb_cFixnum);

In doing some research, it appears this may be due to the fact that Fixnum and Bignum were unified into a single Integer: https://bugs.ruby-lang.org/issues/12005
