### ISSUE TITLE
`rb-gsl` fails to build on Ruby 2.4

### ISSUE THREAD

**Issue by yzyzsun** [SciRuby/rb-gsl#44]
Ruby 2.4 unifies `Fixnum` and `Bignum` into `Integer`, which makes gem native extension broken.

```
$ gem install gsl
Building native extensions.  This could take a while...
ERROR:  Error installing gsl:
	ERROR: Failed to build gem native extension.

……

compiling error.c
In file included from error.c:11:
In file included from ./include/rb_gsl.h:18:
In file included from include/rb_gsl_poly.h:18:
In file included from include/rb_gsl_array.h:27:
In file included from include/rb_gsl_common.h:20:
/usr/local/Cellar/gsl/2.3/include/gsl/gsl_version.h:18:9: warning: 'GSL_VERSION' macro redefined [-Wmacro-redefined]
#define GSL_VERSION "2.3"
        ^
<command line>:1:9: note: previous definition is here
#define GSL_VERSION 2.3
        ^
error.c:83:66: error: use of undeclared identifier 'rb_cFixnum'
  pgsl_error[-2] = rb_define_class_under(mgsl_error, "CONTINUE", rb_cFixnum);
                                                                 ^
error.c:85:64: error: use of undeclared identifier 'rb_cFixnum'
  pgsl_error[0] = rb_define_class_under(mgsl_error, "SUCCESS", rb_cFixnum);
                                                               ^
1 warning and 2 errors generated.
make: *** [error.o] Error 1

make failed, exit code 2
```

**Comment by mvz** [comment]
Any chance of a release that includes this fix?
